name: Build and Test with SBOM
on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'        
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build
  sbom:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: List packages
      run: | 
        dir Docs
        dotnet restore
        dotnet list package >  Docs/packages.csv
    - name: Generate SBOM
      run: |
        dotnet list package --format=csv > Docs/packages.txt
        echo "Packages:"
        cat packages.csv
        spdx-sbom-generator -i Docs/packages.csv -o Docs/sbom.csv
        echo "SBOM:"
        cat Docs/sbom.txt

