name: Build and Test with SBOM
on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.200'        
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build
  sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: List packages
      run: dotnet list package > ./Docs/packages.txt
    - name: Generate SBOM
      run: |
        pwd
        dotnet list package --include-transitive --format=csv > packages.csv
        echo "Packages:"
        cat packages.csv
        spdx-sbom-generator -i packages.csv -o sbom.txt
        echo "SBOM:"
        cat sbom.txt

